<?php
echo '<br>//////////// f_homme_signes.php ///////////<br>';
$tableau['signe']['belier']['text'] = "dynamique, avec un tempérament fougueux qui l’entraine au cœur de l’action, il a tendance à foncer tête baissée dans tout ce qu’il entreprend. Ambitieux, il a un réel besoin d’agir dans son quotidien, ce qui ne l’empêche pas de faire preuve d’une grande générosité. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours";
$tableau['signe']['taureau']['text'] = "simple, sincère et généreux qui aime la vie et en profite au maximum. Bien qu’il prenne le temps de la réflexion avant de se lancer dans des projets, lorsqu’il a pris conscience du bien fondé de ceux-ci, rien ne peut l’arrêter et il ne changera pas d’avis. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours";
$tableau['signe']['gemeaux']['text'] = "observateur et compréhensif qui est motivé par une réelle curiosité d’apprendre. Son esprit ne s’arrête jamais de travailler et il est important qu’il y ait de l’activité dans son quotidien afin qu’il ne puisse pas rester plonger dans ses pensées et se poser trop de questions. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['cancer']['text'] = "imaginatif, émotif avec une nature de rêveur, qui a tendance à vivre dans le passé et à se le ressasser. Cette nostalgie du passé l’amène à rechercher un milieu sûr et où il se sent en sécurité, ce qui ne l’empêche pas de faire preuve d’une bonne humeur communicative. Mais c’est également un homme sensible bien qu’il ne le montre pas toujours.";
$tableau['signe']['lion']['text'] = "déterminé, confiant et décidé, qui est écouté et respecté, et qui est prédestiné à accomplir de grandes choses. Il met toutes les chances de son côté afin de réaliser ses rêves grâce notamment à son audace et à son charisme naturel. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours";
$tableau['signe']['vierge']['text'] = "perfectionniste, raisonnable et prévoyant, qui analyse beaucoup ce qui se déroule autour de lui. Il aime que le travail soit bien fait et n’a de cesse d’essayer d’optimiser les choses en laissant un peu à l’écart la spontanéité. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['balance']['text'] = "===================>perspicace, aimable, avec une tolérance naturelle qui fait de lui une personne qui plait en société du fait qu’il s’adapte facilement. Malgré un caractère qui peut paraître hésitant, c’est un homme qui aime rassembler les gens et pacifier les situations. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['scorpion']['text'] = "ambitieux et persévérant qui aime mettre tous les atouts de son côté afin d’arriver à ses fins. Son caractère indépendant en ce qui concerne les décisions à prendre peut déstabiliser certaines personnes du fait de son besoin d’exister en société. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['sagittaire']['text'] = "dynamique, spontané et indépendant qui a l’âme d’un leader et aime relever les défis qu’il rencontre quotidiennement. Bien qu’il ait de l’ambition et veut réaliser tous ses rêves, il n’en demeure pas moins très sociable. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['capricorne']['text'] = "introverti, indépendant et préférant la solitude. Il peut paraître froid au premier abord, mais est en réalité un homme charmant et sincère. Cette nature réservée lui permet néanmoins de prendre le temps de réfléchir aux situations quotidiennes et l'amène vers une certaine stabilité. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['verseau']['text'] = "généreux, imaginatif et passionné qui aime la vie en société et les relations amicales. Cette nature portée vers l’humain le conduit à s’impliquer dans des projets visant à aider la communauté dans son sens le plus général. Mais il fait également preuve de sensibilité bien qu’il ne le montre pas toujours.";
$tableau['signe']['poisson']['text'] = "bienveillant et compatissant qui n’aime pas les situations conflictuelles. Doté d’une grande imagination, il peut parfois paraître dans les nuages alors qu’il fait preuve de beaucoup de psychologie et est très réfléchi. Mais c’est également un homme sensible bien qu’il ne le montre pas toujours.";
$tableau['signe']['inconnu']['text'] = "doux et sincère même si il n'arrive pas vraiment à mettre en avant ses sentiments. Il fait souvent paraître une image d'indépendance et d'ambition qui font de lui un homme assez difficile à cerner. Mais il est aussi un homme sensible bien qu’il ne le montre pas toujours.";
echo $tableau['signe'][$signe]['text'];
echo $tableau['signe'][$signe2]['text'];

?>