<?php
echo '<br>//////////// homme_signes.php ///////////<br>';
$tableau['signe']['belier']['text'] = 'Dynamique, avec un tempérament fougueux qui vous entraine au cœur de l’action, vous avez tendance à foncer tête baissée dans tout ce que vous entreprenez. Ambitieux, vous avez besoin d’agir dans votre quotidien, ce qui ne vous empêche pas de faire preuve d’une grande générosité.';
$tableau['signe']['taureau']['text'] = 'Simple, sincère et généreux, vous aimez la vie et en profiter au maximum. Bien que vous preniez le temps de la réflexion avant de vous lancer dans des projets, lorsque vous avez pris conscience du bien fondé de ceux-ci, rien ne peut vous arrêter et vous ne changerez pas d’avis.';
$tableau['signe']['gemeaux']['text'] = 'Observateur et compréhensif, vous êtes motivé par une réelle curiosité d’apprendre. Votre esprit ne s’arrête jamais de travailler et il est important qu’il y ait de l’activité dans votre quotidien afin que vous ne puissiez pas rester plonger dans vos pensées et vous poser trop de questions.';
$tableau['signe']['cancer']['text'] = 'Imaginatif, émotif avec une nature de rêveur, vous avez tendance à vivre dans le passé et à vous le ressasser. Cette nostalgie du passé vous amène à rechercher un milieu sûr et où vous vous sentez en sécurité, ce qui ne vous empêche pas de faire preuve d’une bonne humeur communicative.';
$tableau['signe']['lion']['text'] = 'Déterminé, confiant et décidé, vous êtes un homme écouté et respecté, prédestiné à accomplir de grandes choses. Vous mettrez toutes les chances de votre côté afin de réaliser vos rêves grâce notamment à votre audace et à votre charisme naturel.';
$tableau['signe']['vierge']['text'] = 'Perfectionniste, raisonnable et prévoyant, vous êtes un homme qui analyse beaucoup ce qui se déroule autour de lui. Vous aimez que le travail soit bien fait et n’avez de cesse d’essayer d’optimiser les choses en laissant un peu à l’écart la spontanéité.';
$tableau['signe']['balance']['text'] = 'Avec votre perspicacité, votre amabilité et votre tolérance naturelle vous êtes une personne qui plait en société du fait que vous vous adaptez facilement. Malgré un caractère qui peut paraître hésitant, vous êtes un homme qui aime rassembler les gens et pacifier les situations.';
$tableau['signe']['scorpion']['text'] = 'Ambitieux et persévérant, vous aimez mettre tous les atouts de votre côté afin d’arriver à vos fins. Votre caractère indépendant en ce qui concerne les décisions à prendre peut déstabiliser certaines personnes du fait de votre besoin d’exister en société.';
$tableau['signe']['sagittaire']['text'] = 'Dynamique, spontané et indépendant vous avez l’âme d’un leader et aimez relever les défis que vous rencontrez quotidiennement. Bien que vous ayez de l’ambition et vouliez réaliser tous vos rêves, vous n’en demeurez pas moins très sociable.';
$tableau['signe']['capricorne']['text'] = 'Introverti, indépendant et préférant la solitude, vous pouvez paraître froid au premier abord, mais êtes en réalité un homme charmant et sincère. Cette nature réservée vous permet néanmoins de prendre le temps de réfléchir aux situations quotidiennes et vous amène vers une certaine stabilité.';
$tableau['signe']['verseau']['text'] = 'Généreux, imaginatif et passionné, vous êtes un homme qui aime vivre en société et les relations amicales. Cette nature portée vers l’humain vous conduit à vous impliquer dans des projets visant à aider la communauté dans son sens le plus général.';
$tableau['signe']['poisson']['text'] = 'Bienveillant et compatissant vous n’aimez pas les situations conflictuelles. Doté d’une grande imagination, vous pouvez parfois paraître dans les nuages alors que vous faites preuve de beaucoup de psychologie et êtes réfléchi.';
echo $tableau['signe'][$signe]['text'];
echo $tableau['signe'][$signe2]['text'];
?>