<?php
$tableau['signe']['belier']['text'] = 'Indépendante et ambitieuse vous vous donnez les moyens d’obtenir ce que vous désirez. Vous aimez avoir une vie remplie d’aventures et foncez parfois tête baissée sans réfléchir. ';
$tableau['signe']['taureau']['text'] = 'Douce, sincère et fidèle, vous n’aimez néanmoins pas être soumise. Vous avez tendance à ne pas mettre en avant vos sentiments et préférez éviter tous les soucis liés aux relations amoureuses. ';
$tableau['signe']['gemeaux']['text'] = 'Curieuse et compréhensive, vous savez ce que vous voulez. Vous pourrez paraître discrète et froide dans certaines situations, notamment sur le plan sentimental et sur l’engagement.  ';
$tableau['signe']['cancer']['text'] = 'Protectrice et attentionnée vous avez un sens de la famille très présent. De par votre caractère conciliant, vous aurez tendance à être en retrait par rapport à votre entourage, créant un sentiment de distance envers les autres. ';
$tableau['signe']['lion']['text'] = 'Confiante et décidée vous restez néanmoins très réceptive au regard des autres. Vous essayerez souvent de vous mettre en avant, de vous faire remarquer aussi bien des hommes que des femmes et pourrez paraître frivole. ';
$tableau['signe']['vierge']['text'] = 'Réfléchie et en général calme dans le quotidien, vous avez néanmoins un caractère ambitieux qui pourra paraître difficile à cerner du fait de votre envie d’avancer et de la difficulté que vous avez à affirmer votre caractère. ';
$tableau['signe']['balance']['text'] = 'Charmante et perspicace, vous savez vous adapter aux situations du quotidien. Il se peut que vous ayez parfois une attitude assez hautaine envers certains car vous savez que vous êtes séduisante et le ressentez. ';
$tableau['signe']['scorpion']['text'] = 'Indépendante et persuasive grâce à votre aisance à l’oral, vous êtes néanmoins dotée d’un caractère impulsif à certains moments, et pouvez vous renfermer sur vous-même sans donner aucune explication. ';
$tableau['signe']['sagittaire']['text'] = 'Pleine de volonté vous savez exactement ce que vous voulez. Souvent en quête de reconnaissance, il est difficile de vous arrêter lorsque vous avez décidé de quelque chose et avez tendance à vouloir garder une certaine indépendance. ';
$tableau['signe']['capricorne']['text'] = 'Sincère et affectueuse, vous avez besoin de ressentir que vous êtes appréciée ou tout simplement aimée. Vous pouvez parfois vous montrer un peu difficile avec votre proche entourage de par vos petits caprices. ';
$tableau['signe']['verseau']['text'] = 'Indépendante et pleine d’énergie, vous avez tendance à vouloir démontrer que vous arrivez à tout faire seule. Vous avez un réel désir de plaire aux autres et aimez séduire les gens que vous côtoyez ou que vous rencontrez. ';
$tableau['signe']['poisson']['text'] = 'Charmante, vous savez exactement comment vous mettre en valeur. La séduction est un des points essentiels de votre caractère et vous n’hésitez pas à en jouer dans toutes circonstances. ';
?>