<?php
$tableau['signe']['belier']['text'] = "indépendante et ambitieuse qui se donne les moyens d’obtenir ce qu’elle désire. Elle aime avoir une vie remplie d’aventures et fonce parfois tête baissée sans réfléchir. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['taureau']['text'] = "douce, sincère et fidèle mais qui n’aime pas être soumise. Elle aura tendance à ne pas mettre en avant ses sentiments et voudra éviter tous les soucis liés aux relations amoureuses. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['gemeaux']['text'] = "curieuse et compréhensive qui sait ce qu’elle veut. Elle pourra paraître discrète et froide dans certaines situations, notamment sur le plan sentimental et sur l’engagement. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['cancer']['text'] = "protectrice et attentionnée qui a un sens de la famille très présent. De par son caractère conciliant, elle aura tendance à être en retrait par rapport à son entourage, créant un sentiment de distance envers vous. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['lion']['text'] = "confiante et décidée qui reste néanmoins très réceptive au regard des autres. Elle essayera souvent de se mettre en avant, de se faire remarquer aussi bien des hommes que des femmes et pourra paraître frivole. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['vierge']['text'] = "réfléchie et en général calme dans le quotidien. De par son caractère ambitieux, elle pourra paraître difficile à cerner du fait de son envie d’avancer et de la difficulté qu’elle a à affirmer son caractère. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['balance']['text'] = "charmante et perspicace qui sait s’adapter aux situations du quotidien. Elle peut avoir parfois une attitude assez hautaine envers certains car elle sait qu’elle est séduisante et le ressent. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['scorpion']['text'] = "indépendante et persuasive grâce à sa grande aisance à l’oral. Malgré son caractère impulsif à certains moments, elle peut se renfermer sur elle-même sans donner aucune explication. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['sagittaire']['text'] = "pleine de volonté qui sait exactement ce qu’elle veut. Souvent en quête de reconnaissance, il est difficile de l’arrêter lorsqu’elle a décidé de quelque chose et a tendance à vouloir garder une certaine indépendance. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['capricorne']['text'] = "sincère et affectueuse qui a besoin de ressentir qu’elle est appréciée ou tout simplement aimée. Elle peut parfois se montrer un peu difficile avec son proche entourage de par ses petits caprices. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['verseau']['text'] = "indépendante et pleine d’énergie qui peut avoir tendance à vouloir démontrer qu’elle arrive à tout faire seule. Elle a un réel désir de plaire aux autres et aime séduire les gens qu’elle côtoie ou qu’elle rencontre. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['poisson']['text'] = "charmante et qui sait exactement comment se mettre en valeur. La séduction est un des points essentiels de son caractère et elle n’hésite pas à en jouer dans toutes circonstances. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";
$tableau['signe']['inconnu']['text'] = "douce et sincère même si elle n'arrive pas vraiment à mettre en avant ses sentiments. Elle fait souvent paraître une image d'indépendance et d'ambition qui font d'elle une femme assez difficile à cerner. Mais elle est aussi une femme vulnérable et sensible bien qu’elle ne le montre pas toujours.";

?>